version: 1.2
workflows:
   - name: "Deeptools"
     subclass: WDL
     primaryDescriptorPath: /workflows/deeptools/subwf-deeptools.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
             
   - name: "STAR"
     subclass: WDL
     primaryDescriptorPath: /workflows/star/subwf-star.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
             
   - name: "FeatureCounts"
     subclass: WDL
     primaryDescriptorPath: /workflows/featurecount/subwf-featurecount.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
             
   - name: "PicardMergeBams"
     subclass: WDL
     primaryDescriptorPath: /workflows/picard/subwf-mergebams-picard.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
             
   - name: "IterPBS"
     subclass: WDL
     primaryDescriptorPath: /workflows/iterpbs/subwf-iterpbs.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
    
   - name: "DropulationAssignDonors"
     subclass: WDL
     primaryDescriptorPath: /workflows/dropulation/subwf-assign-donors.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/